{% set name = "fifimon" %}
{% set data = load_setup_py_data() %}

package:
  name: "{{ name|lower }}"
  version: "{{ data.get('version') }}"

source:
  git_tag: master
  git_url: https://github.com/darioflute/fifimon.git

build:
  
requirements:
  build:
    - python
    - setuptools

  run:
    - python >=3.7
    - numpy >=1.12.1
    - astropy >=3.0
    - matplotlib >=3.0.2
    
test:
  imports:
    - fifimon

about:
  home: https://github.com/darioflute/fifimon
  license: GPL3
  license_file: LICENSE
  description: 'The package monitors FIFI-LS data'
